# Generated by Django 5.0.2 on 2024-02-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0002_product_checkpoint_product_drive_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='car_body',
        ),
        migrations.AddField(
            model_name='product',
            name='rudder',
            field=models.CharField(choices=[('левый руль', 'левый руль'), ('правый руль', 'правый руль')], default='левый руль', max_length=50, verbose_name='Расположение рулья'),
        ),
        migrations.AlterField(
            model_name='product',
            name='checkpoint',
            field=models.CharField(choices=[('автомат', 'автомат'), ('механика', 'механика')], default='автомат', max_length=15, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='product',
            name='drive_unit',
            field=models.CharField(choices=[('передний привод', 'передний привод'), ('задний привод', 'задний привод'), ('полный привод', 'полный привод')], default='передний привод', max_length=100, verbose_name='Вид топлива'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_of_fuel',
            field=models.CharField(choices=[('бензин', 'бензин'), ('дизель', 'дизель'), ('газ', 'газ'), ('электро', 'электро')], default='передний привод', max_length=15, verbose_name='Привод'),
        ),
    ]
