# Generated by Django 5.0.2 on 2024-02-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0003_remove_product_car_body_product_rudder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='drive_unit',
            field=models.CharField(choices=[('передний привод', 'передний привод'), ('задний привод', 'задний привод'), ('полный привод', 'полный привод')], default='передний привод', max_length=100, verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_of_fuel',
            field=models.CharField(choices=[('бензин', 'бензин'), ('дизель', 'дизель'), ('газ', 'газ'), ('электро', 'электро')], default='бензин', max_length=15, verbose_name='Вид топлива'),
        ),
    ]
