# Generated by Django 5.0.2 on 2024-02-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0006_product_horse_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_speed',
            field=models.PositiveIntegerField(default=0, verbose_name='Максимальная скорость'),
        ),
        migrations.AlterField(
            model_name='product',
            name='horse_power',
            field=models.PositiveIntegerField(default=0, verbose_name='Лошадиные силы'),
        ),
    ]
